/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * users.java
 *
 * Created on 27-jul-2012, 7:02:52
 */
package Clase2;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author NIGHTMARE
 */
public class users extends javax.swing.JFrame {

    /** Creates new form users */
    public users() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontrasenia = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Usuarios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 90, 30);

        jLabel2.setText("Contraseña: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 240, 90, 20);

        jLabel3.setText("Nombre de usuario: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 200, 140, 20);
        getContentPane().add(txtcontrasenia);
        txtcontrasenia.setBounds(220, 240, 120, 20);
        getContentPane().add(txtnombre);
        txtnombre.setBounds(220, 200, 120, 20);

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagen);
        lblImagen.setBounds(180, 60, 110, 110);

        btnEntrar.setText("Entrar");
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(210, 300, 73, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-493)/2, (screenSize.height-413)/2, 493, 413);
    }// </editor-fold>//GEN-END:initComponents

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Eliga una imagen");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int option=chooser.showOpenDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            this.colocarImagen(chooser.getSelectedFile().getAbsolutePath());
        }else{
            JOptionPane.showMessageDialog(this, "No has seleccionado una imagen", "Imagen no seleccionada", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lblImagenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new users().setVisible(true);
            }
        });
    }
    private void colocarImagen(String path){
        ImageIcon imagen=new ImageIcon(path);
        ImageIcon foto=new ImageIcon(imagen.getImage().getScaledInstance(this.lblImagen.getWidth(),this.lblImagen.getHeight(),Image.SCALE_SMOOTH));
        this.lblImagen.setIcon(foto);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtcontrasenia;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
