/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarImagen.java
 *
 * Created on 27-jul-2012, 23:37:46
 */
package Herencia;

/**
 *
 * @author NIGHTMARE
 */
public class AgregarImagen extends javax.swing.JFrame {
    Image imgs[]=new Image[10];
    /** Creates new form AgregarImagen */
    public AgregarImagen() {
        initComponents();
        imgs[0]=new Reflexion_Image("Hola","Esto es una prueba","C:/Users/NIGHTMARE/Pictures/Chistes/251816_345731485504094_1980963477_n.jpg");
        imgs[1]=new Other_Image("Mundo","Esta es la segunda prueba","C:/Users/NIGHTMARE/Pictures/Chistes/561411_456641657689783_1252566430_n.jpg");
        VisorImagenes temp=new VisorImagenes(imgs,0,2);
        temp.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-544)/2, (screenSize.height-458)/2, 544, 458);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AgregarImagen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
