/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 27-jul-2012, 23:06:21
 */
package Herencia;

import javax.swing.ImageIcon;

/**
 *
 * @author NIGHTMARE
 */
public class VisorImagenes extends javax.swing.JFrame {

    private int pos;
    private int mode;
    private int tam;
    Image values[];
    /** Creates new form Interfaz */
    public VisorImagenes(Image v[],int m,int t) {
        initComponents();
        this.mode=m;
        this.pos=0;
        this.tam=t;
        this.values=v;
        loadInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        rdbNumber4 = new javax.swing.JRadioButton();
        rdbNumber1 = new javax.swing.JRadioButton();
        rdbNumber2 = new javax.swing.JRadioButton();
        rdbNumber3 = new javax.swing.JRadioButton();
        lblTitle = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnteriorMouseClicked(evt);
            }
        });
        getContentPane().add(btnAnterior);
        btnAnterior.setBounds(50, 200, 50, 50);

        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(610, 200, 50, 50);

        lblImagen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(153, 0, 0));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblImagen);
        lblImagen.setBounds(130, 80, 440, 310);

        rdbNumber4.setText("jRadioButton1");
        getContentPane().add(rdbNumber4);
        rdbNumber4.setBounds(470, 420, 93, 23);

        rdbNumber1.setText("jRadioButton1");
        getContentPane().add(rdbNumber1);
        rdbNumber1.setBounds(140, 420, 93, 23);

        rdbNumber2.setText("jRadioButton1");
        getContentPane().add(rdbNumber2);
        rdbNumber2.setBounds(250, 420, 93, 23);

        rdbNumber3.setText("jRadioButton1");
        getContentPane().add(rdbNumber3);
        rdbNumber3.setBounds(360, 420, 93, 23);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel2");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(230, 20, 260, 40);

        lblImagen1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblImagen1.setForeground(new java.awt.Color(153, 0, 0));
        lblImagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen1.setText("No hay imagen disponible");
        lblImagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblImagen1);
        lblImagen1.setBounds(130, 80, 440, 310);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-708)/2, (screenSize.height-545)/2, 708, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        if(pos<tam-1){
            pos++;
            this.loadInfo();
        }
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnteriorMouseClicked
        if(pos>0){
            pos--;
            this.loadInfo();
        }
    }//GEN-LAST:event_btnAnteriorMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rdbNumber1;
    private javax.swing.JRadioButton rdbNumber2;
    private javax.swing.JRadioButton rdbNumber3;
    private javax.swing.JRadioButton rdbNumber4;
    // End of variables declaration//GEN-END:variables

    private void loadInfo() {
        colocarImagen(values[pos].getPath());
        this.lblTitle.setText(values[pos].getNombre());
        this.lblImagen.setToolTipText(values[pos].getDescription());
    }

    private void colocarImagen(String path) {
        ImageIcon img=new ImageIcon(path);
        ImageIcon foto=new ImageIcon(img.getImage().getScaledInstance(this.lblImagen.getWidth(),this.lblImagen.getHeight(), 1));
        this.lblImagen.setIcon(foto);
    }
}
