/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Save_Info.java
 *
 * Created on 10-ago-2012, 7:08:16
 */
package GenerarObjetos;

import javax.swing.JFileChooser;

/**
 *
 * @author NIGHTMARE
 */
public class Save_Info extends javax.swing.JFrame {

    Users lista[];
    int cant=10;
    int pos;
    String path;
    
    /** Creates new form Save_Info */
    public Save_Info() {
        initComponents();
        iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        rdbF = new javax.swing.JRadioButton();
        rdbM = new javax.swing.JRadioButton();
        btnImagen = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guardar Información");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 270, 80);

        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 40);

        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 160, 80, 40);

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(170, 170, 130, 20);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(170, 130, 130, 20);

        rdbF.setText("Femenino");
        rdbF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbFMouseClicked(evt);
            }
        });
        getContentPane().add(rdbF);
        rdbF.setBounds(120, 260, 93, 23);

        rdbM.setText("Masculino");
        rdbM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbMMouseClicked(evt);
            }
        });
        rdbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMActionPerformed(evt);
            }
        });
        getContentPane().add(rdbM);
        rdbM.setBounds(120, 220, 110, 23);

        btnImagen.setText("Imagen");
        btnImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagenMouseClicked(evt);
            }
        });
        getContentPane().add(btnImagen);
        btnImagen.setBounds(90, 330, 90, 50);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(230, 330, 90, 50);

        txtVisualizar.setText("Ver");
        txtVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVisualizarMouseClicked(evt);
            }
        });
        getContentPane().add(txtVisualizar);
        txtVisualizar.setBounds(230, 230, 90, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-394)/2, (screenSize.height-496)/2, 394, 496);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void rdbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMActionPerformed

    private void rdbFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbFMouseClicked
        this.rdbF.setSelected(true);
        this.rdbM.setSelected(false);
    }//GEN-LAST:event_rdbFMouseClicked

    private void rdbMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbMMouseClicked
        this.rdbF.setSelected(false);
        this.rdbM.setSelected(true);
    }//GEN-LAST:event_rdbMMouseClicked

    private void btnImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagenMouseClicked
        JFileChooser selected=new JFileChooser();
        selected.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int option=selected.showOpenDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            this.path=selected.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_btnImagenMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String name=this.txtNombre.getText();
        String dir=this.txtDireccion.getText();
        char Sex=(this.rdbM.isSelected()?'M':'F');
        this.lista[this.pos++]=new Users(name,dir,Sex,this.path);
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void txtVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVisualizarMouseClicked
        View_Users temp=new View_Users(this.lista,this.pos);
        temp.setVisible(true);
    }//GEN-LAST:event_txtVisualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Save_Info().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rdbF;
    private javax.swing.JRadioButton rdbM;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JButton txtVisualizar;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.lista=new Users[this.cant];        
        this.pos=0;
        this.rdbM.setSelected(true);
        path=" ";
    }
}
