/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * View_Users.java
 *
 * Created on 10-ago-2012, 7:37:36
 */
package GenerarObjetos;

import java.awt.Container;

public class View_Users extends javax.swing.JFrame {
    Container contenedorPrincipal;
    Container contenedores[][];
    Object objetos[][];
    Users usuarios[];
    int cant;
    public View_Users(Users us[],int cant) {
        initComponents();
        this.usuarios=us;
        this.cant=cant;
        iniciar();
        crearObjetos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-351)/2, (screenSize.height-542)/2, 351, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar() {
        this.contenedorPrincipal=new Container();
        this.contenedores=new Container[this.cant][2];
        this.objetos=new Object[this.cant][4];
    }

    private void crearObjetos() {
        for(int i=0;i<this.cant;i++){
            
        }
    }

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
